config/routes.rb
Rails.application.routes.draw do

  root 'statics#landing_page'
  resources :prelaunchsubscribers

end

app/models/prelaunchsubscriber.rb
class Prelaunchsubscriber < ActiveRecord::Base
end

app/models/static.rb
class Static < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/prelaunchsubscribers_controller.rb
class PrelaunchsubscribersController < ApplicationController
  before_action :set_prelaunchsubscriber, only: [:show, :edit, :update, :destroy]

  # GET /prelaunchsubscribers
  # GET /prelaunchsubscribers.json
  def index
    @prelaunchsubscribers = Prelaunchsubscriber.all
  end

  # GET /prelaunchsubscribers/1
  # GET /prelaunchsubscribers/1.json
  def show
  end

  # GET /prelaunchsubscribers/new
  def new
    @prelaunchsubscriber = Prelaunchsubscriber.new
  end

  # GET /prelaunchsubscribers/1/edit
  def edit
  end

  # POST /prelaunchsubscribers
  # POST /prelaunchsubscribers.json
  def create
    @prelaunchsubscriber = Prelaunchsubscriber.new(prelaunchsubscriber_params)

    respond_to do |format|
      if @prelaunchsubscriber.save
        format.html { redirect_to @prelaunchsubscriber, notice: 'Prelaunchsubscriber was successfully created.' }
        format.json { render :show, status: :created, location: @prelaunchsubscriber }
        format.js
      else
        format.html { render :new }
        format.json { render json: @prelaunchsubscriber.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /prelaunchsubscribers/1
  # PATCH/PUT /prelaunchsubscribers/1.json
  def update
    respond_to do |format|
      if @prelaunchsubscriber.update(prelaunchsubscriber_params)
        format.html { redirect_to @prelaunchsubscriber, notice: 'Prelaunchsubscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @prelaunchsubscriber }
      else
        format.html { render :edit }
        format.json { render json: @prelaunchsubscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prelaunchsubscribers/1
  # DELETE /prelaunchsubscribers/1.json
  def destroy
    @prelaunchsubscriber.destroy
    respond_to do |format|
      format.html { redirect_to prelaunchsubscribers_url, notice: 'Prelaunchsubscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prelaunchsubscriber
      @prelaunchsubscriber = Prelaunchsubscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prelaunchsubscriber_params
      # params.fetch(:prelaunchsubscriber, {:emailid => :emailid})
      params.required(:prelaunchsubscriber).permit(:emailid)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  before_action :set_static, only: [:show, :edit, :update, :destroy]

  def landing_page
    @prelaunchsubscriber = Prelaunchsubscriber.new
  end
  
  # GET /statics
  # GET /statics.json
  def index
    @statics = Static.all
  end

  # GET /statics/1
  # GET /statics/1.json
  def show
  end

  # GET /statics/new
  def new
    @static = Static.new
  end

  # GET /statics/1/edit
  def edit
  end

  # POST /statics
  # POST /statics.json
  def create
    @static = Static.new(static_params)

    respond_to do |format|
      if @static.save
        format.html { redirect_to @static, notice: 'Static was successfully created.' }
        format.json { render :show, status: :created, location: @static }
      else
        format.html { render :new }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statics/1
  # PATCH/PUT /statics/1.json
  def update
    respond_to do |format|
      if @static.update(static_params)
        format.html { redirect_to @static, notice: 'Static was successfully updated.' }
        format.json { render :show, status: :ok, location: @static }
      else
        format.html { render :edit }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statics/1
  # DELETE /statics/1.json
  def destroy
    @static.destroy
    respond_to do |format|
      format.html { redirect_to statics_url, notice: 'Static was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static
      @static = Static.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_params
      params.fetch(:static, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prelaunchsubscribers_helper.rb
module PrelaunchsubscribersHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comingsoon</title>
  <%= stylesheet_link_tag   'http://fonts.googleapis.com/css?family=Quicksand', 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/prelaunchsubscribers/_form.html.erb
<%= form_for(@prelaunchsubscriber) do |f| %>
  <% if @prelaunchsubscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prelaunchsubscriber.errors.count, "error") %> prohibited this prelaunchsubscriber from being saved:</h2>

      <ul>
      <% @prelaunchsubscriber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prelaunchsubscribers/edit.html.erb
<h1>Editing Prelaunchsubscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @prelaunchsubscriber %> |
<%= link_to 'Back', prelaunchsubscribers_path %>

app/views/prelaunchsubscribers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prelaunchsubscribers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prelaunchsubscribers.each do |prelaunchsubscriber| %>
      <tr>
        <td><%= link_to 'Show', prelaunchsubscriber %></td>
        <td><%= link_to 'Edit', edit_prelaunchsubscriber_path(prelaunchsubscriber) %></td>
        <td><%= link_to 'Destroy', prelaunchsubscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prelaunchsubscriber', new_prelaunchsubscriber_path %>

app/views/prelaunchsubscribers/new.html.erb
<h1>New Prelaunchsubscriber</h1>

<%= render 'form' %>

<%= link_to 'Back', prelaunchsubscribers_path %>

app/views/prelaunchsubscribers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_prelaunchsubscriber_path(@prelaunchsubscriber) %> |
<%= link_to 'Back', prelaunchsubscribers_path %>

app/views/statics/landing_page.html.erb
	<section class="content wrapper" style="padding-top:10px;">

		<h1 class="brandtext"><span>Rento</span><span class="brandhalftextcolor">monk</span></h1>
		<p class="description">We are building an exciting new product to make your life easier. Please join our newsletter so that we can get in touch with you once we launch.</p>

		<div class="subscription_form clearfix">
			<div>
<!-- 				<form action="http://pixelhint.us3.list-manage.com/subscribe/post?u=9cf3b8b1cfc597a436b9964d3&amp;id=2449ed590e" method="post" id="sub_form">
					<input type="email" id="mc-email" placeholder="enter your email">
					<button type="submit" id="mc_submit"><i class="icon"></i></button>
				</form> -->

				<%= form_for(@prelaunchsubscriber, remote: true, id: "sub_form") do |f| %>
				<%= f.text_field :emailid %>
				<%= button_tag(type: "submit") do %>
					<i class="icon"></i>
				<% end %>
				<% end %>

			</div>
		</div>

		<div class="counter clear" data-date="2016-10-31 00:00:00"></div>

	</section>
	